### ISSUE TITLE
Create Login page

### ISSUE THREAD

**Issue by DecrepitSonar** [DecrepitSonar/AmpleApp#1]

**Comment by KingKianooo** [comment]
Any specific theme colour for the app yet? so the login page can be made accordingly.?

**Comment by DecrepitSonar** [comment]
> Any specific theme colour for the app yet? so the login page can be made accordingly.?

the primary color of the app is  255, 227, 77  in rgb. the app bgColor is gonna be 22, 22, 22 which is a black ish color. but for now its white so use whatever colors u want. can always change later

**Comment by KingKianooo** [comment]
Okay
